<?php
/**
 * @param array $settings
 */
function ckeditor_moono_blue_skin_editor_js_settings_alter(array &$settings) {
    foreach (array_keys($settings['editor']['formats']) as $text_format_id) {
        if ($settings['editor']['formats'][$text_format_id]['editor'] === 'ckeditor') {
            $settings['editor']['formats'][$text_format_id]['editorSettings']['skin'] = 'moono-blue,/libraries/ckeditor/skins/moono-blue/';
        }
    }
}
